export const UPDATE_CUSTOM_EVENT = 'UPDATE_CUSTOM_EVENT' ;
export const UPDATE_CUSTOM_EVENT_LOADING = 'UPDATE_CUSTOM_EVENT_LOADING' ;
export const UPDATE_CUSTOM_EVENT_ERROR = 'UPDATE_CUSTOM_EVENT_ERROR' ;